# Generated by Django 3.0.4 on 2020-03-26 08:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='booking',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='fms.Booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='vehicle',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='fms.Vehicle'),
            preserve_default=False,
        ),
    ]
