# Generated by Django 3.0.4 on 2020-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_auto_20200326_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='remarks',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
