# Generated by Django 3.0.4 on 2020-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_auto_20200326_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
