# Generated by Django 3.0.4 on 2020-03-26 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='from_location',
            field=models.TextField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='to_location',
            field=models.TextField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
