# Generated by Django 3.0.4 on 2020-03-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_auto_20200328_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='fms.Status'),
        ),
    ]
